[package]
name = "rustotp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.29.0"
totp-rs = "5.7.0"

[profile.release]
codegen-units = 1
lto = "fat"
